//  Главная страница на карточках товара отображает первые восемь фотографий, 
//  заполнять свойство images нужно в таком порядке: с 1 по 4 фотографии сумки
//  первого цвета, с 5 по 8 сумки коричневого цвета

const cardsData = [
  {
    itemName: 'Дорожная сумка "Бочонок"',
    color: "черный или коричневый",
    width: "45",
    height: "18",
    depth: "29",
    capacity: "25",
    weight: "1",
    category: "bochonok",
    inside:
      "одно основное отделение, карман на липучке для нэтбука/планшета, карман на молнии, два маленьких кармана открытого типа",
    outside: "два передних кармана на молнии, один сзади на молнии",
    bottom: "усилено",
    stripe: "регулируемый, длина 90-165 см",
    material: "экокожа",
    images: [
      'https://револди.рф/images/bag_pictures/bochonok_black/1-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/2-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/3-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/4-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/5-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/6-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/7-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/8-min.png',
      'https://револди.рф/images/bag_pictures/bochonok_black/9-min.png',
      'https://револди.рф/images/bag_pictures/bochonok_black/10-min.png',
      'https://револди.рф/images/bag_pictures/bochonok_black/11-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/12-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/13-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_black/14-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/1-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/2-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/3-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/4-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/5-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/6-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/7-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/8-min.png',
      'https://револди.рф/images/bag_pictures/bochonok_brown/9-min.png',
      'https://револди.рф/images/bag_pictures/bochonok_brown/10-min.png',
      'https://револди.рф/images/bag_pictures/bochonok_brown/11-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/12-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/13-min.jpg',
      'https://револди.рф/images/bag_pictures/bochonok_brown/14-min.jpg',
    ],
  },
  {
    itemName: 'Дорожная сумка "Дипломат"',
    color: "черный или коричневый",
    width: "45",
    height: "18",
    depth: "29",
    capacity: "25",
    weight: "1",
    category: "diplomat",
    inside:
      "одно основное отделение, карман на липучке для нэтбука/планшета, карман на молнии, два маленьких кармана открытого типа",
    outside:
      "два передних кармана на молнии, один сзади широкий на молнии, два боковых на кнопке",
    bottom: "усилено",
    stripe: "регулируемый, длина 90-165 см",
    material: "экокожа",
    images: [
      'https://револди.рф/images/bag_pictures/diplomat_black/1-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/2-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/3-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/4-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/5-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/6-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/7-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/8-min.png',
      'https://револди.рф/images/bag_pictures/diplomat_black/9-min.png',
      'https://револди.рф/images/bag_pictures/diplomat_black/10-min.png',
      'https://револди.рф/images/bag_pictures/diplomat_black/11-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/12-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/13-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_black/14-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/1-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/2-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/3-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/4-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/5-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/6-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/7-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/8-min.png',
      'https://револди.рф/images/bag_pictures/diplomat_brown/9-min.png',
      'https://револди.рф/images/bag_pictures/diplomat_brown/10-min.png',
      'https://револди.рф/images/bag_pictures/diplomat_brown/11-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/12-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/13-min.jpg',
      'https://револди.рф/images/bag_pictures/diplomat_brown/14-min.jpg',
    ],
  },
  {
    itemName: 'Дорожная сумка "Саквояж"',
    color: "черный или коричневый",
    width: "45",
    height: "18",
    depth: "29",
    capacity: "25",
    weight: "1",
    category: "valise",
    inside:
      "одно основное отделение, карман на липучке для нэтбука/планшета, карман на молнии, два маленьких кармана открытого типа",
    outside: "карман спереди на кнопке, сзади карман на молнии",
    bottom: "усилено",
    stripe: "регулируемый, длина 90-165 см",
    material: "экокожа",
    images: [
      'https://револди.рф/images/bag_pictures/valise_black/1-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/2-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/3-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/4-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/5-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/6-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/7-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/8-min.png',
      'https://револди.рф/images/bag_pictures/valise_black/9-min.png',
      'https://револди.рф/images/bag_pictures/valise_black/10-min.png',
      'https://револди.рф/images/bag_pictures/valise_black/11-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/12-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/13-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_black/14-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/1-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/2-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/3-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/4-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/5-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/6-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/7-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/8-min.png',
      'https://револди.рф/images/bag_pictures/valise_brown/9-min.png',
      'https://револди.рф/images/bag_pictures/valise_brown/10-min.png',
      'https://револди.рф/images/bag_pictures/valise_brown/11-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/12-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/13-min.jpg',
      'https://револди.рф/images/bag_pictures/valise_brown/14-min.jpg',
    ],
  },
  {
    itemName: 'Дорожная сумка "Ручная кладь"',
    color: "черный или коричневый",
    width: "50",
    height: "20",
    depth: "30",
    capacity: "30",
    weight: "1.3",
    category: "hand_luggage",
    inside:
      "одно основное отделение, карман на липучке для нэтбука/планшета, карман на молнии, два маленьких кармана открытого типа",
    outside: "карман спереди по всю ширину на молнии, сзади на молнии",
    bottom: "усилено",
    stripe: "регулируемый, длина 85-150 см",
    material: "экокожа",
    images: [
      'https://револди.рф/images/bag_pictures/hand_luggage_black/1-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/2-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/3-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/4-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/5-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/6-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/7-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/8-min.png',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/9-min.png',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/10-min.png',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/11-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/12-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/13-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_black/14-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/1-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/2-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/3-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/4-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/5-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/6-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/7-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/8-min.png',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/9-min.png',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/10-min.png',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/11-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/12-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/13-min.jpg',
      'https://револди.рф/images/bag_pictures/hand_luggage_brown/14-min.jpg',
    ],
  },
  {
    itemName: 'Дорожная сумка "Спортивная"',
    color: "черный или коричневый",
    width: "50",
    height: "25",
    depth: "30",
    capacity: "40",
    weight: "1.3",
    category: "sport",
    inside:
      "одно основное отделение, два небольших кармана открытого типа, один карман на молнии",
    outside: "одно отделение для обуви сбоку, один карман на молнии сбоку",
    bottom: "усилено, имеет ножки",
    stripe: "регулируемый, длина 85-150 см",
    material: "экокожа",
    images: [
      'https://револди.рф/images/bag_pictures/sport_black/1-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/2-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/3-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/4-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/5-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/6-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/7-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/8-min.png',
      'https://револди.рф/images/bag_pictures/sport_black/9-min.png',
      'https://револди.рф/images/bag_pictures/sport_black/10-min.png',
      'https://револди.рф/images/bag_pictures/sport_black/11-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/12-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/13-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_black/14-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/1-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/2-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/3-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/4-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/5-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/6-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/7-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/8-min.png',
      'https://револди.рф/images/bag_pictures/sport_brown/9-min.png',
      'https://револди.рф/images/bag_pictures/sport_brown/10-min.png',
      'https://револди.рф/images/bag_pictures/sport_brown/11-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/12-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/13-min.jpg',
      'https://револди.рф/images/bag_pictures/sport_brown/14-min.jpg',
    ],
  },
  {
    itemName: 'Дорожная сумка "Классика"',
    color: "черный или коричневый",
    width: "50",
    height: "20",
    depth: "30",
    capacity: "30",
    weight: "1.3",
    category: "classic",
    inside:
      "одно основное отделение, два небольших кармана открытого типа, один карман на молнии",
    outside: "два передних кармана на молнии",
    bottom: "усилено, имеет ножки",
    stripe: "регулируемый, длина 85-150 см",
    material: "экокожа",
    images: [
      'https://револди.рф/images/bag_pictures/classic_black/1-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/2-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/3-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/4-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/5-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/6-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/7-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/8-min.png',
      'https://револди.рф/images/bag_pictures/classic_black/9-min.png',
      'https://револди.рф/images/bag_pictures/classic_black/10-min.png',
      'https://револди.рф/images/bag_pictures/classic_black/11-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/12-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/13-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_black/14-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/1-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/2-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/3-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/4-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/5-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/6-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/7-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/8-min.png',
      'https://револди.рф/images/bag_pictures/classic_brown/9-min.png',
      'https://револди.рф/images/bag_pictures/classic_brown/10-min.png',
      'https://револди.рф/images/bag_pictures/classic_brown/11-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/12-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/13-min.jpg',
      'https://револди.рф/images/bag_pictures/classic_brown/14-min.jpg',
    ],
  },
];

export { cardsData };
